version: "3.9"

services:
  angular_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/angular-app"
    command: ["npm", "start"]
    ports:
      - "8081:8081"
    volumes:
      - "$PWD/angular-app:/angular-app"
