version: "3.9"

services:
  angular_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - "8088:4200"
    volumes:
      - "$PWD/angular-app:/angular-app"
